### ISSUE TITLE
服务器名

### ISSUE THREAD

**Issue by SkeletonCold** [SkeletonCold/server#11]
云之天地

**Comment by SkeletonCold** [comment]
已弃用“云之天地”

**Comment by XuanYuSLF** [comment]
海の都

**Comment by XuanYuSLF** [comment]
海代表自由，都代表群组

**Comment by SkeletonCold** [comment]
> 海の都

8太行，还有，带入你这个语境，很容易被误解为“dou”，像是带入“天空都市”这种语境，就不会被误解

**Comment by liuzihang520** [comment]
南 瓜

**Comment by liuzihang520** [comment]
南瓜灯很好看

**Comment by artoriay** [comment]
彩虹之诗？

**Comment by SkeletonCold** [comment]
终末之诗
岩石之令




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SkeletonCold/server"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 晚上6:04
收件人:&nbsp;"SkeletonCold/server"<server@noreply.github.com&gt;;
抄送:&nbsp;"小白的梦"<3033573504@qq.com&gt;;"Assign"<assign@noreply.github.com&gt;;
主题:&nbsp;Re: [SkeletonCold/server] 服务器名 (#11)





 
彩虹之诗？

**Comment by XuanYuSLF** [comment]
终末之诗可以awa
