### ISSUE TITLE
[其他]

### ISSUE THREAD

**Issue by XuanYuSLF** [SkeletonCold/server#18]
如何核心套核心已有fabric和bukkit的兼容mod

**Comment by SkeletonCold** [comment]
我不是很理解您的意思
如果您想同时运行fabric mod&bukkit插件在您的服务器上
您可以试试[此模组](https://www.mcmod.cn/class/3267.html)，将其放置于fabric服务端下的mods文件夹中，重启您的服务器！
您的服务端将会以bukkit服务端的形式启动，原存档也会自动迁移（比如说原存档中的下界【dim-1】他将自动存为world_nether并保留所以数据！）
**警告：该模组仍处于早期测试阶段，极其不稳定，慎用！**

**Comment by XuanYuSLF** [comment]
https://github.com/CardboardPowered/cardboard/discussions

**Comment by XuanYuSLF** [comment]
这个用法和你所诉的一样吗(

**Comment by SkeletonCold** [comment]
我们说的同一个东西
他原名是fabric4bukkit，现在更名了
**可能已经脱离早期测试阶段**

**Comment by XuanYuSLF** [comment]
吆西，是要让fabric自动安装那个原版的核心，然后
把mod放进去

**Comment by XuanYuSLF** [comment]
是这样吗awa

**Comment by XuanYuSLF** [comment]
肝
点错了

**Comment by SkeletonCold** [comment]
感谢您的回复
看起来您似乎还没正确安装fabric服务端
请详细阅读[此教程](https://skeletoncold.github.io/post/how-to-install-minecraft-server/)

**Comment by XuanYuSLF** [comment]
okay

**Comment by SkeletonCold** [comment]
已将此问题打开，如有其他疑问
欢迎回复！

**Comment by XuanYuSLF** [comment]
为什么ikuuu对于浏览网页，只能在隐身窗口有效?

**Comment by SkeletonCold** [comment]
不知道，我这边正常的
只是有的时候不起效了，重启浏览器之后就好了

**Comment by XuanYuSLF** [comment]
az,我一直不起效

**Comment by XuanYuSLF** [comment]
hi

**Comment by XuanYuSLF** [comment]
能迁移一下账号吗，我入正了awa,账号名叫XuanYuSLF

**Comment by SkeletonCold** [comment]
最好不要在close的问题下回复
还有，wsm正版名字要和离线的不一样啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊
要是一样的话，我都不用去搞，你直接就是那样= =
真说的话搞起来也不麻烦就是....但是我不想去整

**Comment by XuanYuSLF** [comment]
因为被取过了((((((((

**Comment by SkeletonCold** [comment]
:(
刚刚付了3个月的映射会员费（-60CNY）
希望有人能给我发发电（
