### ISSUE TITLE
玩家数据转移qwq

### ISSUE THREAD

**Issue by XuanYuSLF** [SkeletonCold/server#19]
打算寒假搞凋零骷髅塔，还有，地面上出现白线(可能是锯齿)怎么解决啊
![%NXR`$X7V%%RD%XG$44095R](https://user-images.githubusercontent.com/77571440/105317389-1b6e5080-5bfd-11eb-8bf7-733ea13e315c.png)

**Comment by SkeletonCold** [comment]
右键桌面-NVDIA控制面板-3D设置-程序设置-java.exe或者javaw.exe---
---各向异性过滤-关闭

**Comment by XuanYuSLF** [comment]
关全局也行吧

**Comment by SkeletonCold** [comment]
我不知道，可能其他游戏会出问题
我自己是对单个程序设置的
关于玩家数据迁移...晚点吧

**Comment by XuanYuSLF** [comment]
![image](https://user-images.githubusercontent.com/77571440/105318055-fe864d00-5bfd-11eb-89bb-434460d30d38.png)

**Comment by XuanYuSLF** [comment]
好吧

**Comment by SkeletonCold** [comment]
浏览
一般默认c盘
programfiles-java-1.8.xxx-bin-java.exe
