### ISSUE TITLE
[客户端]客户端v2.0.0(Beta)

### ISSUE THREAD

**Issue by DeitiesCold** [SkeletonCold/server#24]
玄理2下不了，在HMCL上。

**Comment by SkeletonCold** [comment]
请自行更换下载源或网络代理
该问题不在讨论范围内，自行解决
**后续可能会推出完整客户端**
即拥有完整资源文件的客户端，不过会非常的大，所以才打包成现在这样

**Comment by SkeletonCold** [comment]
将在下个版本修复
 - 添加使用说明
 - 添加EULA
 - **推出完整客户端**
 - PCL自定义主题更新
